### ISSUE TITLE
Razón Social y Nombre Comercial

### ISSUE THREAD

**Issue by joguenco** [renbenj9/l10n-ecuador#8]
En el archivo account_edi_document.py

`social_name = "PRUEBAS SERVICIO DE RENTAS INTERNAS"
 business_name = "PRUEBAS SERVICIO DE RENTAS INTERNAS"
 if environment == "2":
            social_name = self._l10n_ec_clean_str(company.partner_id.name)
            business_name = self._l10n_ec_clean_str(
                company.partner_id.l10n_ec_business_name or social_name
            )`
Cuando se activa en modo producción aparece un error del business_name

**Comment by mestizosdev** [comment]
Forma de pago en factura de venta
Al momento de emitir una factura de venta, no existe la opción de elegir una forma de pago, y se crea con la forma de pago por default

**Comment by celm1990** [comment]
Corregido en el commit https://github.com/renbenj9/l10n-ecuador/commit/473984e1afb827d202aab0e91eb4ca719b9e1e8a
